# Generated by Django 4.0.5 on 2022-11-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='hello', max_length=100),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='name',
            field=models.CharField(default='hello', max_length=100),
        ),
        migrations.AddField(
            model_name='question_paper',
            name='name',
            field=models.CharField(default='hello', max_length=100),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='Answer',
            field=models.CharField(choices=[('option1', models.CharField(max_length=10)), ('option2', models.CharField(max_length=10)), ('option3', models.CharField(max_length=10)), ('option4', models.CharField(max_length=10))], max_length=10),
        ),
    ]
