# Generated by Django 4.0.5 on 2022-11-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_name_examquestion_name_question_paper_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
