# Generated by Django 4.0.5 on 2022-11-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_examquestion_name_remove_question_paper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
