# Generated by Django 4.0.5 on 2022-11-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_stu_question_stuexam_db_sturesults_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='description',
            new_name='question',
        ),
    ]
