# Generated by Django 4.0.5 on 2022-11-20 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_examquestion_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 11, 27, 65648)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(default=datetime.datetime(2022, 11, 20, 11, 11, 27, 65648)),
        ),
    ]
