# Generated by Django 4.0.5 on 2022-11-20 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_exam_end_time_alter_exam_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 12, 35, 31, 880237)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 12, 35, 31, 880237)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
