# Generated by Django 4.0.5 on 2022-11-22 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_exam_end_time_alter_exam_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 10, 7, 17, 948256)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 10, 7, 17, 948256)),
        ),
        migrations.AlterField(
            model_name='stu_question',
            name='choice',
            field=models.CharField(default='5', max_length=3),
        ),
    ]
