# Generated by Django 4.0.5 on 2022-07-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='nothing', max_length=256),
            preserve_default=False,
        ),
    ]
