# Generated by Django 4.0.5 on 2022-12-20 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('course', models.CharField(blank=True, default='', max_length=256)),
                ('course_html', models.TextField(blank=True, default='', editable=False)),
                ('code', models.CharField(editable=False, max_length=255)),
                ('members', models.ManyToManyField(related_name='members', through='classroom.ClassMember', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='classmember',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='classroom.classroom'),
        ),
        migrations.AddField(
            model_name='classmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classmember',
            unique_together={('classroom', 'user')},
        ),
    ]
