# Generated by Django 4.0.5 on 2022-10-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_classroom_code_remove_classroom_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='hello', editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classroom',
            name='course_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
