# Generated by Django 4.0.5 on 2022-10-12 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('classroom', '0005_alter_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='members',
            field=models.ManyToManyField(related_name='members', through='classroom.ClassMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
