# Generated by Django 4.0.5 on 2022-10-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_classroom_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
