# Generated by Django 4.0.5 on 2022-10-26 11:12

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignmentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='media'),
        ),
    ]
