# Generated by Django 4.0.5 on 2022-11-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_alter_assignmentsubmission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='turn_in_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
