# Generated by Django 4.0.5 on 2022-11-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_assignmentsubmission_turn_in_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='turn_in_status',
            field=models.CharField(max_length=10),
        ),
    ]
