# Generated by Django 4.0.5 on 2022-11-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='turn_in_status',
            field=models.CharField(default='timely', max_length=10),
        ),
    ]
